In [ ]:
import logistic_reg
reload(logistic_reg)
from logistic_reg import *

Missing data train set:
PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64
Missing data test set:
PassengerId    0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.205742
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.002392
Cabin          0.782297
Embarked       0.000000
dtype: float64
Titles:
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Mlle              2
Col               2
Major             2
Lady              1
Jonkheer          1
Don               1
Ms                1
Mme               1
Capt              1
the Countess      1
Sir               1
Name: Title, dtype: int64

Missing data train set:
Cabin    687
dtype: int64

Missing data test set:
Cabin    327
dtype: int64
0
0
              Fare  Survived
Fare      1.000000  0.251627
Survived  0.251627  1.000000
Survived               0   1
Title        Pclass
Aristocratic 1         7   8
             2         8   0
Master       1         0   3
             2         0   9
             3        17  11
Miss         1         2  47
             2         2  32
             3        51  51
Mr           1        70  37
             2        83   8
             3       283  36
Mrs          1         1  41
             2         4  38
             3        21  21
Missing data train set:
PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64
Missing data test set:
PassengerId    0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.205742
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.002392
Cabin          0.782297
Embarked       0.000000
dtype: float64
Titles:
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Mlle              2
Col               2
Major             2
Lady              1
Jonkheer          1
Don               1
Ms                1
Mme               1
Capt              1
the Countess      1
Sir               1
Name: Title, dtype: int64

Missing data train set:
Cabin    687
dtype: int64

Missing data test set:
Cabin    327
dtype: int64
0
0
              Fare  Survived
Fare      1.000000  0.251627
Survived  0.251627  1.000000
Survived               0   1
Title        Pclass
Aristocratic 1         7   8
             2         8   0
Master       1         0   3
             2         0   9
             3        17  11
Miss         1         2  47
             2         2  32
             3        51  51
Mr           1        70  37
             2        83   8
             3       283  36
Mrs          1         1  41
             2         4  38
             3        21  21
                        0    1
TicketType  Survived
0           0         410  410
            1         255  255
A./5.       0           2    2
A.5.        0           2    2
A/4         0           3    3
A/4.        0           3    3
A/5         0           9    9
            1           1    1
A/5.        0           6    6
            1           1    1
A/S         0           1    1
A4.         0           1    1
C           0           3    3
            1           2    2
C.A.        0          14   14
            1          13   13
C.A./SOTON  0           1    1
CA          0           6    6
CA.         0           7    7
            1           1    1
F.C.        0           1    1
F.C.C.      0           1    1
            1           4    4
Fa          0           1    1
P/PP        0           1    1
            1           1    1
PC          0          21   21
            1          39   39
PP          0           1    1
            1           2    2
S.C./A.4.   0           1    1
S.C./PARIS  0           1    1
            1           1    1
S.O./P.P.   0           3    3
S.O.C.      0           5    5
S.O.P.      0           1    1
S.P.        0           1    1
S.W./PP     1           1    1
SC          1           1    1
SC/AH       0           1    1
            1           1    1
SC/AH Basle 1           1    1
SC/PARIS    0           3    3
            1           2    2
SC/Paris    0           2    2
            1           2    2
SCO/W       0           1    1
SO/C        1           1    1
SOTON/O.Q.  0           7    7
            1           1    1
SOTON/O2    0           2    2
SOTON/OQ    0           6    6
            1           1    1
STON/O 2.   0           7    7
            1           5    5
STON/O2.    0           3    3
            1           3    3
SW/PP       1           1    1
W./C.       0           8    8
            1           1    1
W.E.P.      0           1    1
W/C         0           1    1
WE/P        0           1    1
            1           1    1
['f1', 'f1_weighted', 'f1_samples', 'recall_samples', 'recall_micro', 'adjusted_rand_score', 'recall_macro', 'mean_absolute_error', 'precision_macro', 'precision_weighted', 'f1_macro', 'recall_weighted', 'accuracy', 'precision_samples', 'median_absolute_error', 'precision', 'log_loss', 'precision_micro', 'average_precision', 'roc_auc', 'r2', 'recall', 'mean_squared_error', 'f1_micro']
5
3
2
Missing data train set:
PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64
Missing data test set:
PassengerId    0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.205742
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.002392
Cabin          0.782297
Embarked       0.000000
dtype: float64
Titles:
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Mlle              2
Col               2
Major             2
Lady              1
Jonkheer          1
Don               1
Ms                1
Mme               1
Capt              1
the Countess      1
Sir               1
Name: Title, dtype: int64

Missing data train set:
Cabin    687
dtype: int64

Missing data test set:
Cabin    327
dtype: int64
0
0
              Fare  Survived
Fare      1.000000  0.251627
Survived  0.251627  1.000000
Survived               0   1
Title        Pclass
Aristocratic 1         7   8
             2         8   0
Master       1         0   3
             2         0   9
             3        17  11
Miss         1         2  47
             2         2  32
             3        51  51
Mr           1        70  37
             2        83   8
             3       283  36
Mrs          1         1  41
             2         4  38
             3        21  21
                        0    1
TicketType  Survived
0           0         410  410
            1         255  255
A./5.       0           2    2
A.5.        0           2    2
A/4         0           3    3
A/4.        0           3    3
A/5         0           9    9
            1           1    1
A/5.        0           6    6
            1           1    1
A/S         0           1    1
A4.         0           1    1
C           0           3    3
            1           2    2
C.A.        0          14   14
            1          13   13
C.A./SOTON  0           1    1
CA          0           6    6
CA.         0           7    7
            1           1    1
F.C.        0           1    1
F.C.C.      0           1    1
            1           4    4
Fa          0           1    1
P/PP        0           1    1
            1           1    1
PC          0          21   21
            1          39   39
PP          0           1    1
            1           2    2
S.C./A.4.   0           1    1
S.C./PARIS  0           1    1
            1           1    1
S.O./P.P.   0           3    3
S.O.C.      0           5    5
S.O.P.      0           1    1
S.P.        0           1    1
S.W./PP     1           1    1
SC          1           1    1
SC/AH       0           1    1
            1           1    1
SC/AH Basle 1           1    1
SC/PARIS    0           3    3
            1           2    2
SC/Paris    0           2    2
            1           2    2
SCO/W       0           1    1
SO/C        1           1    1
SOTON/O.Q.  0           7    7
            1           1    1
SOTON/O2    0           2    2
SOTON/OQ    0           6    6
            1           1    1
STON/O 2.   0           7    7
            1           5    5
STON/O2.    0           3    3
            1           3    3
SW/PP       1           1    1
W./C.       0           8    8
            1           1    1
W.E.P.      0           1    1
W/C         0           1    1
WE/P        0           1    1
            1           1    1
['f1', 'f1_weighted', 'f1_samples', 'recall_samples', 'recall_micro', 'adjusted_rand_score', 'recall_macro', 'mean_absolute_error', 'precision_macro', 'precision_weighted', 'f1_macro', 'recall_weighted', 'accuracy', 'precision_samples', 'median_absolute_error', 'precision', 'log_loss', 'precision_micro', 'average_precision', 'roc_auc', 'r2', 'recall', 'mean_squared_error', 'f1_micro']
5
3
2
['TitleCat', 'Pclass', 'SexCat', 'Age', 'Fare', 'EmbarkedCat', 'SibSp', 'Parch', 'Family', 'IsFamily', 'CabinLetterCat', 'CabinNumber']

In [ ]:
# lets divide group on sex groups
# how good we can do?
groups = data_train.groupby('Sex').groups 
males = groups['male']
females = groups['female']

p = solver.predict(data_train[males])
class_report(data_train[males].Survived, p)

print "hello"